# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



pool:
  Default

steps:

- task: Service@2
  inputs:
    ServiceName: 'DemoService'
    Action: 'Stop'
    AdminUserName: 'SVP/dsonavaria'
    AdminPassword: 'Welcome2019!!'
    MachineNameslist: 'USCORE01DEV'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: Service@2
  inputs:
    ServiceName: 'DemoService'
    Action: 'Start'
    AdminUserName: 'SVP/dsonavaria'
    AdminPassword: 'Welcome2019!!'
    MachineNameslist: 'USCORE01DEV'


