# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



pool:
  Default

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '\\USCORE01dev\d$\Portfolio'

- script: sc \\USCORE01DEV start DemoService

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

- script: sc \\USCORE01DEV Stop DemoService


